name: Deploy to Server
on : 
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  auto-deploy:
    name: auto deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: get latest code
      uses: actions/checkout@v3
      
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.1
      with:
        server: 103.150.116.73
        username: skripsi_sely
        password: 3jyTW2MxAsfDmASi
        port: 21
        protocol: ftp
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/storage/imports/**
          **/vendor/**
          **/venv/**
          